export const PACKAGE_CATEGORIES = {
  adventure: "Adventure",
  cultural: "Cultural",
  beach: "Beach",
  mountain: "Mountain",
  heritage: "Heritage",
  wildlife: "Wildlife",
} as const

export const INDIAN_STATES = [
  "Kanyakumari (Tamil Nadu)",
  "Kerala",
  "Karnataka",
  "Goa",
  "Maharashtra",
  "Gujarat",
  "Rajasthan",
  "Uttar Pradesh",
  "Uttarakhand",
  "Himachal Pradesh",
  "Punjab",
  "Jammu & Kashmir",
] as const

export const TOUR_PACKAGES = [
  {
    id: 1,
    title: "Kerala Backwaters & Beaches",
    category: "beach",
    price: 24999,
    duration: "5 days",
    image: "/kerala-backwaters-houseboat.png",
    description: "Experience the serene backwaters and pristine beaches of Kerala",
    locations: ["Kochi", "Alleppey", "Munnar"],
  },
  {
    id: 2,
    title: "Rajasthan Royal Heritage Tour",
    category: "heritage",
    price: 34999,
    duration: "7 days",
    image: "/taj-mahal-agra-palace.jpg",
    description: "Explore the majestic palaces and forts of Rajasthan",
    locations: ["Delhi", "Agra", "Jaipur", "Pushkar"],
  },
  {
    id: 3,
    title: "Himalayan Adventure Trek",
    category: "adventure",
    price: 29999,
    duration: "6 days",
    image: "/himalayan-mountains-trek.jpg",
    description: "Trek through the stunning Himalayan ranges",
    locations: ["Rishikesh", "Auli", "Chopta"],
  },
  {
    id: 4,
    title: "Goa Beach Paradise",
    category: "beach",
    price: 19999,
    duration: "4 days",
    image: "/goa-beach-sunset.jpg",
    description: "Relax on the golden beaches of Goa",
    locations: ["North Goa", "South Goa", "Panjim"],
  },
  {
    id: 5,
    title: "Kashmir Valley Escape",
    category: "mountain",
    price: 39999,
    duration: "8 days",
    image: "/kashmir-dal-lake-mountains.jpg",
    description: "Discover the paradise of Kashmir with stunning landscapes",
    locations: ["Srinagar", "Gulmarg", "Pahalgam", "Sonmarg"],
  },
  {
    id: 6,
    title: "Wildlife Safari - Ranthambore",
    category: "wildlife",
    price: 27999,
    duration: "5 days",
    image: "/tiger-safari-ranthambore.jpg",
    description: "Spot the majestic Bengal tiger in its natural habitat",
    locations: ["Ranthambore", "Sawai Madhopur"],
  },
]
